In [35]:
# Importer le librairies nécessaires 
import numpy as np #Pour tout ce qui est mathématiques 
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression # Car on va utiliser une regression linéaire

In [36]:
#Emplacemnet du fichier courant
import os
os.getcwd()

'C:\\Users\\COMPTABILITE\\Desktop\\Mes formations\\Machine Learning avec Youtube\\Code Source et Data'

In [37]:
#Importer le dataset
Data = pd.read_excel('datas/VoitureOccasion.xlsx')

X = Data.iloc[:, :-1]
Y = Data.iloc[:, -1]

In [38]:
Data

,Année,Kilométrage,Nb chevaux,Marque,Prix
0,2005,250000,6,Audi,90000
1,2004,215000,7,Audi,85000
2,2010,145000,8,BMW,110000
3,2015,90000,6,BMW,130000
4,2017,65000,9,Mercedes,160000
5,2012,150000,7,BMW,120000
6,2010,160000,7,Audi,95000
7,2012,155000,7,Mercedes,120000
8,2015,85000,6,BMW,132000
9,2018,52000,6,Mercedes,175000


In [39]:
X

,Année,Kilométrage,Nb chevaux,Marque
0,2005,250000,6,Audi
1,2004,215000,7,Audi
2,2010,145000,8,BMW
3,2015,90000,6,BMW
4,2017,65000,9,Mercedes
5,2012,150000,7,BMW
6,2010,160000,7,Audi
7,2012,155000,7,Mercedes
8,2015,85000,6,BMW
9,2018,52000,6,Mercedes


In [40]:
Y

0      90000
1      85000
2     110000
3     130000
4     160000
5     120000
6      95000
7     120000
8     132000
9     175000
10    140000
11    140000
12    135000
13    155000
14    210000
15    111000
16     90000
17    105000
18    165000
19    190000
20    110000
21    100000
22    115000
23    115000
24    120000
25    110000
26    170000
27    195000
28    180000
29    220000
30    113500
31    145500
32    124500
33    125000
34    135000
35    135000
36    145000
37    190000
38    176000
39    205000
40    120000
41    117000
42    125000
43    168000
44    188000
45    180000
46    215000
47    113500
48    145500
Name: Prix, dtype: int64

In [41]:
#Gérer les variables catégoriques
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer # Permet d'appliquer des transformations sur certaines colonnes spécifiques

# 3 c'est l'indice de la colone Marque sachant que la première colonne a poiyr indice 0
# remainder='passthrough' # Garde les autres colonnes sans modification
ct = ColumnTransformer([("Marque", OneHotEncoder(), [3])], remainder='passthrough' )
X = ct.fit_transform(X)

In [42]:
X

array([[1.000e+00, 0.000e+00, 0.000e+00, 2.005e+03, 2.500e+05, 6.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.004e+03, 2.150e+05, 7.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.010e+03, 1.450e+05, 8.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.015e+03, 9.000e+04, 6.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.017e+03, 6.500e+04, 9.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.012e+03, 1.500e+05, 7.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.010e+03, 1.600e+05, 7.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.012e+03, 1.550e+05, 7.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.015e+03, 8.500e+04, 6.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.018e+03, 5.200e+04, 6.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.014e+03, 1.300e+05, 7.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.013e+03, 1.300e+05, 7.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.013e+03, 1.700e+05, 6.000e+00],
       [0.000e+00, 0.000e

In [43]:
#Diviser le dataset
X_train, X_test, Y_train, Y_test =  train_test_split(X, Y, test_size=0.2)

In [44]:
X_train

array([[0.000e+00, 0.000e+00, 1.000e+00, 2.014e+03, 1.740e+05, 8.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.011e+03, 1.400e+05, 7.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.011e+03, 2.050e+05, 7.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.018e+03, 4.500e+04, 7.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.019e+03, 5.500e+04, 7.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.017e+03, 8.400e+04, 6.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.010e+03, 2.100e+05, 6.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.012e+03, 1.900e+05, 8.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.018e+03, 4.500e+04, 7.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.017e+03, 6.500e+04, 9.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.014e+03, 1.680e+05, 6.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.017e+03, 8.400e+04, 6.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.014e+03, 1.800e+05, 8.000e+00],
       [0.000e+00, 1.000e

In [45]:
#Construire le modèle
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression()

In [46]:
#Faire des prédictions
Y_pred = regressor.predict(X_test)

In [47]:
Y_pred

array([111202.16254782,  59043.29839932, 176658.61310129, 125071.9546971 ,
       109005.53722429,  94261.72684344,  90455.69504848, 159422.86187863,
       207248.29234918, 178471.61645681])

In [48]:
Y_test

23    115000
0      90000
45    180000
33    125000
17    105000
2     110000
16     90000
43    168000
9     175000
13    155000
Name: Prix, dtype: int64

In [49]:
#Prédire une voiture qui n'existe pas dans noter dtatset
                #    Marque(Mercedes)	   Année  Kilométrage Nb chevaux
regressor.predict([ [0, 0, 1,               2021,     9000,       6 ] ])

array([238737.79763642])

In [50]:
#Prédire une  seconde voiture qui n'existe pas dans noter dtatset
                #    Marque(Mercedes)	   Année  Kilométrage Nb chevaux
regressor.predict([ [0, 1, 0,               2012,     98000,       3 ] ])

array([153872.48382064])